#!/usr/bin/env python3
"""Rows of the action-score ablation table, generated from the saved run.

Reads results/gates/action_family*.json and prints the table body, so no number
in the paper is transcribed by hand. Column order matches Table 3's.
"""
import json, sys, os

BENCH = ('AVE', 'NinaPro', 'PTB-XL', 'IEMOCAP', 'DrugBAN')
FAM = ('logistic', 'tree3', 'forest', 'knn25', 'mlp16')
FEAT = ('baseconf', 'baseent', 'targetconf', 'agree', 'l1')
LABEL = {'logistic': 'logistic (deployed)', 'tree3': 'decision tree, depth $3$',
         'forest': 'random forest, $200$ trees', 'knn25': '$k$NN, $k=25$',
         'mlp16': 'MLP, one hidden layer of $16$',
         'baseconf': 'base confidence', 'baseent': 'base entropy',
         'targetconf': 'target confidence', 'agree': 'agreement flag',
         'l1': '$\\ell_1$ distance'}


def load(paths):
    out = {}
    for p in paths:
        if os.path.exists(p):
            for k, v in json.load(open(p)).items():
                out.setdefault(k, {}).update(v)
    return out


def cell(v):
    return '---' if v is None else f"${v['gain']:+.3f}$/${v['harm']:.2f}$"


def block(d, names, labels):
    for n, lab in zip(names, labels):
        row = [cell(d.get(b, {}).get(n)) for b in BENCH]
        print(f"{lab:32s} & " + ' & '.join(row) + ' \\\\')


d = load(sys.argv[1:])
print('% gain/joint harm at alpha=0.2; generated by scripts/tables/action_rows.py')
print('\\multicolumn{6}{@{}l}{\\emph{Score family, all five features}}\\\\')
block(d, FAM, [LABEL[f] for f in FAM])
print('\\midrule')
print('\\multicolumn{6}{@{}l}{\\emph{Logistic score, one feature removed}}\\\\')
block(d, [f'drop:{f}' for f in FEAT], [f'without {LABEL[f]}' for f in FEAT])
if any(f'keep:{FEAT[0]}' in d.get(b, {}) for b in BENCH):
    print('\\midrule')
    print('\\multicolumn{6}{@{}l}{\\emph{Logistic score, one feature only}}\\\\')
    block(d, [f'keep:{f}' for f in FEAT], [f'{LABEL[f]} only' for f in FEAT])
print('% cells: ' + ', '.join(f"{b} {d.get(b,{}).get('cells','?')}" for b in BENCH))
